server:
  port: 9050


cloud:

  aws:
    region:
      static: ${AWS_Region}       
    credentials:
      access-key: ${AWSAccessKeyId}
      secret-key: ${AWSSecretKey}
    stack:
      auto: false
    
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        
spring:
  
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration  
  datasource:
    url: jdbc:postgresql://${ERS_DB_ENDPOINT}/${ERS_DB_DBNAME}
    
    username: ${ERS_DB_USERNAME}
    password: ${ERS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    
  
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
#      ddl-auto: create-drop
#       ddl-auto: create
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ${ERS_GMAIL_USERNAME}
    password: ${ERS_GMAIL_PASSWORD}
    properties:
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true
    protocol: smtp
    test-connection: false
      
