server:
  port: 9050
 
spring:
  
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: jdbc:postgresql://${ERS_DB_ENDPOINT}/${ERS_DB_DBNAME}
    
    username: ${ERS_DB_USERNAME}
    password: ${ERS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    
  
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
#      ddl-auto: create-drop
#       ddl-auto: create
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: user987456321789
    password: obgppatovkyrbdfn
    properties:
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true
    protocol: smtp
    test-connection: false
      
